version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emwiki
    volumes:
      - ./docker/pgsql-data:/var/lib/postgresql/data
    expose:
      - "5432"
  python:
    build: .
    volumes:
      - ./docker/static:/code/static
      - ./emwiki/mizarfiles:/code/emwiki/mizarfiles
    expose:
      - "8001"
    depends_on:
      - db
  nginx:
    image: nginx:1.17
    ports:
      - "8000:8000"
    volumes:
      - ./docker:/etc/nginx/conf.d
      - ./docker/uwsgi_params:/etc/nginx/uwsgi_params
      - ./docker/static:/static
    depends_on:
      - python
  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080
    depends_on: 
      - db