version: '3'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
  python:
    build:
      context: ./
      dockerfile: Dockerfile
    command: uwsgi --chdir=/workspace/emwiki --module emwiki.wsgi --env DJANGO_SETTINGS_MODULE=emwiki.settings --socket :8001
    volumes:
      - .:/workspace:cached
      - static-volume:/workspace/emwiki/staticfiles
      - media-volume:/workspace/emwiki/mediafiles
      - emwiki-contents-volume:/workspace/emwiki/contents/mizarfiles/emwiki-contents:cached
    expose:
      - "8001"
    env_file:
      - .env
    depends_on:
      - db
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports: 
      - 8080:8080
    depends_on: 
      - db
  nginx:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    environment: 
      DOMAINS: 'localhost'
      # STAGE: 'production' # Don't use production until staging works
    volumes:
      - ./nginx/nginx.ssl.conf:/var/lib/nginx-conf/localhost.ssl.conf.erb:ro
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - static-volume:/staticfiles
      - media-volume:/mediafiles
    depends_on: 
      - python

volumes:
    postgres-data:
    static-volume:
    media-volume:
    emwiki-contents-volume: