version: '3'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
  python:
    build:
      context: ./
      dockerfile: Dockerfile
    command: uwsgi --chdir=./workspace/emwiki --module emwiki.wsgi --env DJANGO_SETTINGS_MODULE=emwiki.settings --socket :8001
    volumes:
      - .:/workspace:cached
      - static-volume:/workspace/emwiki/staticfiles
      - media-volume:/workspace/emwiki/mediafiles
      - emwiki-contents-volume:/workspace/emwiki/contents/mizarfiles/emwiki-contents:cached
    expose:
      - "8001"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - static-volume:/staticfiles
      - media-volume:/mediafiles
    depends_on:
      - python
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    environment: 
      DOMAINS: 'localhost->http://nginx:8000'
      # STAGE: 'production' # Don't use production until staging works
    depends_on: 
      - nginx

volumes:
    postgres-data:
    static-volume:
    media-volume:
    emwiki-contents-volume:
