version: '3'

services:
  # python:
  #   image: python:3.7
  #   volumes:
  #     - ..:/~
  #   env_file:
  #     - .env
  #   command: sleep infinity
  #   network_mode: service:db
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports: 
      - 8080:8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports: 
      - 8080:8080
    depends_on: 
      - db
