version: '3'

services:
  python:
    build:
      context: ..
      dockerfile: ./.prodcontainer/Dockerfile
    volumes:
      - ..:/workspace/emwiki:cached
      - static-volume:/workspace/emwiki/emwiki/staticfiles
      - media-volume:/workspace/emwiki/emwiki/mediafiles
    expose:
      - "8001"
    command: pipenv run uwsgi --chdir=/workspace/emwiki/emwiki --mount /emwiki=/workspace/emwiki/emwiki/emwiki/wsgi.py --manage-script-name --env DJANGO_SETTINGS_MODULE=emwiki.settings --socket :8001
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - "5432"
  nginx:
    image: nginx:latest
    expose:
      - "8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - static-volume:/staticfiles
      - media-volume:/mediafiles
    depends_on:
      - python
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    environment: 
      DOMAINS: 'emwiki->http://nginx:8000'
      STAGE: 'local'
      # STAGE: 'production' # Don't use production until staging works
    depends_on: 
      - nginx

volumes:
    postgres-data:
    static-volume:
    media-volume:
    emwiki-contents-volume:
